### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by bchalk101**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bchalk101** [comment]
@conda-forge-admin, please rerender

**Comment by hajapy** [comment]
Hi @bchalk101, looks like you are testing out the recipe for a pre-release version? I see a couple minor issues here:

1. The license file is not packaged with the pypi source dist. That could be resolved upstream as part of packaging for pypi or we can include a copy here. Are you in position to resolve the packaging issue on the upstream project ahead of 6.3.0 release?
2. We don't normally release pre-releases on conda-forge AFAIK, but if this is just for testing then that is fine. Otherwise, I don't think we'd intend to merge/release until 6.3.0 lands.
3. It looks like the change to 6.3.0 changes the imports from `argo.workflows` to `argo_worklows`, so the test import is failing here.

**Comment by bchalk101** [comment]
Hey @hajapy,

I've made a PR with argo-workflows, which has been merged and waiting on them to make a RC release that will include the License.

There is a secondary PR, https://github.com/conda-forge/hera-workflows-feedstock/pull/10, which depends on the RC hence the pr for RC. Is there a reason for not merging RC's into conda-forge?

Will update the imports.

**Comment by hajapy** [comment]
Here is the guidance I can find around pre-releases: https://github.com/conda-forge/cfep/blob/main/cfep-05.md

The specification section describes what I think would need to change here to accommodate a rc release. We could always ask someone from core to provide more guidance, as I have not encountered this in other packages I help maintain.

**Comment by bchalk101** [comment]
Hey @hajapy,
From what I can see in the argo-workflows github repo, this conforms to a rc release as set out by the above guidance. There are no more feature changes and currently only bug fixes and doc changes for this release.

Following the guidance here: https://conda-forge.org/docs/maintainer/knowledge_base.html#pre-release-builds, I have changed the label to `_rc`.

I believe the last step is for this to be merged into a branch called `rc` rather than master. So if you could pls create that branch I can set this PR to merge into it :smile:

**Comment by hajapy** [comment]
@bchalk101 I've added you as a maintainer and updated the rendering of the feedstock on master.

You should now be able to update this PR to get the minimal diff (or create a new one) then create the rc branch with those changes included (before you push the branch). Importantly that latest change with the rc label should be present on the rc branch's first push. There cannot really be a code review for creating/pushing the branch, but what I see here looks right minus the changes that are no longer needed (maintainer  + re-rendering). I also bumped build number just in case the commit would cause a new build, so you can drop that back to 0 on rc.

**Comment by hajapy** [comment]
@bchalk101 also you need to re-render after updating recipe/conda_build_config.yaml

**Comment by hajapy** [comment]
@conda-forge-admin please rerender

**Comment by hajapy** [comment]
Ok this is a bit messy. Here's what I propose.

1. Close this PR
2. Create a new branch in personal fork (not named rc) with just necessary changes as discussed above and open new pr here. 
3. We can "approve" those changes, then that branch can be used to create the rc branch which you can then push directly to this repo.

**Pull request closed without merging**
