### PR TITLE
Update to 5.0.0, add self as maintainer

### PR DESCRIPTION
**Pull request by hajapy**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hajapy** [comment]
@conda-forge-admin, please rerender

**Comment by hadim** [comment]
Can you also remove me as a maintainer?

**Comment by hajapy** [comment]
@conda-forge-admin, please rerender

**Comment by hadim** [comment]
Please confirm, it's ready to merge.

**Comment by hajapy** [comment]
@hadim Yep, I think it's ready. Thanks! 

(I can't find any other undeclared requirements)

**Pull request merged**
