### PR TITLE
Changes for approval to create rc branch

### PR DESCRIPTION
**Pull request by bchalk101**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bchalk101** [comment]
@conda-forge-admin, please rerender

**Comment by bchalk101** [comment]
@hajapy I believe this is the min required merge - Once u look over it will push this onto a new `rc` branch 😄

**Comment by hajapy** [comment]
The changes look clean & correct to me! If I were doing this, I'd probably clean up the git history with a rebase/squash, but I won't hold up your efforts unless you want to do this. Feel free to create the rc branch from this when you are ready.

I do recommend following up with it to ensure the files were published and have the appropriate label on https://anaconda.org/conda-forge/argo-workflows after that is done (so do it when you have time to watch this). If for whatever reason something went wrong, please create an issue so we can discuss / call for assistance there.

**Comment by bchalk101** [comment]
Closing as completed by `rc` branch and label appearing here: https://anaconda.org/conda-forge/argo-workflows/labels

**Comment by hajapy** [comment]
Nice! Glad it all worked out. Good to learn about this process as well, while slightly cumbersome I can see how it can be useful. Looks like some pretty big changes coming in the next Argo workflows release.

**Pull request closed without merging**
